### ISSUE TITLE
Filtering statistics and endpoints

### ISSUE THREAD

**Issue by nabsul** [mac-/hapi-statsd#17]
First of all, great work on this plugin. It works flawlessly and does a great job.

We are looking to use it and need to find a way to limit which endpoints we generate statistics on. We need a way to define which endpoints get statsd metrics, and which status codes. I have several questions about this:
- Are there any plans to add such a feature?
- If not, do you recommend any other implementations?
- If not, and if we fork and develop such options, would you be interested in reviewing and merging them into this plugin?

We're asking these questions to decide whether we should attempt to contribute to this code base, or go with our own implementation.

Thanks!

**Comment by mac-** [comment]
That sounds like a great idea, and I would welcome any contributions for those changes!

**Comment by nabsul** [comment]
FYI, we're working on the update here: https://github.com/Automattic/hapi-statsd/pull/1
