### ISSUE TITLE
timing information not getting logged correctly

### ISSUE THREAD

**Issue by rwinbush** [mac-/hapi-statsd#22]
`statsdClient.timing(statName, startDate);`

Shouldn't that be something like:
`statsdClient.timing(statName, new Date() - startDate);`

Otherwise you are just logging the start date and not the actual time it took to execute.

**Comment by mac-** [comment]
I guess it depends on which statsd client you are using. If you are using the one that this module depends on, then it does the `new Date() - startDate` automatically for you when you pass in a Date.
